stages:
  - build

full:
  image: dcurylo/fsharp-mono-netcore
  stage: build
  script:
    - mono .paket/paket.exe restore
    - dotnet restore src/
    - dotnet build src/
    - dotnet restore test/
    - dotnet build test/
    - dotnet run --project test/SimpleDiff.Test.fsproj
