stages:
  - build

full:
  image: dcurylo/fsharp-mono-netcore
  stage: build
  script:
    - mono .paket/paket.exe restore
    - dotnet restore
    - dotnet build
    - dotnet run --project test/SimpleDiff.Test.fsproj
