name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '3.1.x', '5.0.x' ]

    steps:
    - uses: actions/checkout@v2

    - name: Set up .NET SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet-version }}

    - name: Set up Paket
      run: dotnet tool install --tool-path .paket paket

    - name: Restore dependencies
      run: .paket/paket restore

    - name: Run tests
      run: dotnet test --verbosity minimal
